### ISSUE TITLE
Webview error The operation couldn't be completed. 

### ISSUE THREAD

**Issue by LOG-TAG** [razorpay/razorpay-flutter#41]
ERROR: 0 Webview error The operation couldn't be completed.
(NSURLErrorDomain error -999.)

ON ios latest version of razerpay any idea why this happened?

![WhatsApp Image 2019-10-29 at 7 33 42 PM](https://user-images.githubusercontent.com/1190344/67828711-6b459100-fafa-11e9-842f-d978d6ece62e.jpeg)

**Comment by sumedht** [comment]
We have fixed this issue with our latest version of SDK. Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by appscriplaxminarayana** [comment]
![Skype_Picture_2022_10_10T09_14_10_964Z](https://user-images.githubusercontent.com/88077481/194833629-fa80a4dd-782b-459f-b597-ea1d90059961.jpeg)
I'm Still getting this error.
razorpay_flutter: ^1.3.2

**Comment by shahrukhioux** [comment]
We are using latest razorpay_flutter: ^1.3.4 but still we are getting this error.
