### ISSUE TITLE
Unable to run application after installing razorpay_flutter : 1.3.7 (Android)

### ISSUE THREAD

**Issue by afitjulapis** [razorpay/razorpay-flutter#422]
I've added razorpay_flutter : 1.3.7 as dependency and was unable to run or build the application 

The error i received upon building is :

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     error: failed processing manifest.

## Flutter Version 
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.6 23G80 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/hyperanalytics/fvm/versions/3.24.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (2 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/hyperanalytics/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

Im hoping this is because of a silly mistake on my part. Any input is appreciated

**Comment by aavhanchatse** [comment]
I'm also facing the same issue. After removing the razorpay library, the project is running successfully. Can someone help ?

**Comment by vivekshindhe** [comment]
@afitjulapis @aavhanchatse Can you folks please share the entire error log?

**Comment by afitjulapis** [comment]
Thank you for the prompt reply, sure.

## Building via VSCode :
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     error: failed processing manifest.
2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Error: Gradle task assembleDebug failed with exit code 1



## Building via Android Studio :
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     /Users/hyperanalytics/Desktop/FlutterWorks/gm_private/build/app/intermediates/packaged_manifests/debug/AndroidManifest.xml:161: error: resource style/Theme.AppCompat.NoActionBar (aka com.example.go_malaysia:style/Theme.AppCompat.NoActionBar) not found.
     error: failed processing manifest.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by vivekshindhe** [comment]
@afitjulapis @aavhanchatse Can you folks, please sync gradle once or a couple of times, or just reinstall the razorpay-flutter package and try again? This should be resolved now.

**Comment by Pavithran-python** [comment]
@afitjulapis @aavhanchatse  implementation 'androidx.appcompat:appcompat:1.7.0' Add this library in app/build.gradle. 
![image](https://github.com/user-attachments/assets/b7a6e2c3-b9c5-4f69-aa85-db306e0be681)

**Comment by afitjulapis** [comment]
> @afitjulapis @aavhanchatse Can you folks, please sync gradle once or a couple of times, or just reinstall the razorpay-flutter package and try again? This should be resolved now.

Hi @vivekshindhe , i've rebuild my gradle and reinstalled razorpay multiple times , but it seems like the same error is still there. Im using gradle 7.6.3.

**Comment by afitjulapis** [comment]
> @afitjulapis @aavhanchatse implementation 'androidx.appcompat:appcompat:1.7.0' Add this library in app/build.gradle. ![image](https://private-user-images.githubusercontent.com/65224586/390814447-b7a6e2c3-b9c5-4f69-aa85-db306e0be681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDYyMTEsIm5iZiI6MTczMjg0NTkxMSwicGF0aCI6Ii82NTIyNDU4Ni8zOTA4MTQ0NDctYjdhNmUyYzMtYjljNS00ZjY5LWFhODUtZGIzMDZlMGJlNjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAyMDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYjY4M2M2MjBjNmRkNzcxYWUyNTJmZGQyZDc5ZDRiMjdjYTkzMThjYWZlMjFhOGJhMTcyYzBmNDc0NzU5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m2feLChE8zGTaKRNSNKG7FyOeWWomc2QvNWMlpWIbLQ)

Hi @Pavithran-python , i tried your suggestion but it leads me to a different error. I've included the error log if youre interested to look into it. Thank you again for your suggestion


## Built via VSCode
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
         > Error while dexing.

**Comment by vivekshindhe** [comment]
@afitjulapis So the reason the error was happening because an internal dependency was using 

> style/Theme.AppCompat.NoActionBar

We have now removed this and the internal dependency now uses 

> @android:style/Theme.Translucent.NoTitleBar

We verified this from our end and the fix was working. 
The reason for the re-installation of the razorpay-flutter package was to ensure that the package is picking the latest version of the dependency.

**Comment by afitjulapis** [comment]
I've ran another flutter clean and reinstalled razorpay. Now it builds succesfully. Thanks @vivekshindhe.

**Comment by vivekshindhe** [comment]
@afitjulapis Thanks for the update. closing the ticket.
